### ISSUE TITLE
The error occurs Remove `{ output: 'export' }`

### ISSUE THREAD

**Issue by miyapt** [xizon/fullstack-nextjs-app-template#1]
I just ran the project npm run dev
and it shows

Error: Image Optimization using the default loader is not compatible with `{ output: 'export' }`.
  Possible solutions:
    - Remove `{ output: 'export' }` and run "next start" to run server mode including the Image Optimization API.
    - Configure `{ images: { unoptimized: true } }` in `next.config.js` to disable the Image Optimization API.
  Read more: https://nextjs.org/docs/messages/export-image-api
    at getImgProps (webpack-internal:///./node_modules/next/dist/shared/lib/get-img-props.js:241:19)
    at eval (webpack-internal:///./node_modules/next/dist/client/image-component.js:272:82)

**Comment by xizon** [comment]
Thanks. fixed it & Upgrade to [next 14+](https://nextjs.org/docs/pages/building-your-application/upgrading/version-14).

**Comment by xizon** [comment]
Try it. My local test has been Okay. If it happens again, tell me nodejs or other more information :)

**Comment by xizon** [comment]
This bug has been fixed. Try it :)
